.gitignore
lua/plugins/init.lua

doom.log keeps showing up as modified, even though logs/ is in the .gitignore file.
This change removes doom.log and adds it specifically to the .gitignore file.
Second commit removes the 'lua' branch from indent-blankline to prevent warning popup, moving the plugin to master.

maint: remove logs/doom.log, update indent-blankline

---

install.sh

/usr/bin/bash and /bin/bash aren't guaranteed to exist on many systems, but /usr/bin/env is. This change makes the shebang line /usr/bin/env bash so it works on any modern *nix type system.  Tested in macOS, Ubuntu and WSL.

use /usr/bin/env bash to make install more portable

---

lua/doom/modules/config/doom-gitsigns.lua

update the gitsigns setup according to this changes
<https://github.com/lewis6991/gitsigns.nvim/commit/34deec281323c14c20a6f44070d4c1f668dfb2b0>

fix(gitsigns): `use_internal_diff` has been replaced with `diff_opts.internal`

---

lua/doom/modules/config/doom-cmp.lua
lua/doom/modules/config/doom-lsp-signature.lua
lua/doom/modules/config/doom-lspinstall.lua
lua/doom/modules/config/doom-luasnip.lua
lua/doom/utils/init.lua

also lazyload everything and fix lsp_signature
Fixes #112

[Refactor]: use nvim-cmp instead of compe

---

lua/doom/modules/init.lua

this way we are making sure to load snippets before nvim-cmp to avoid unexpected issues
also make sure that lsp_signature is lazy loaded

[Bugfix] make sure plugins are loaded in a correct order

---

lua/doom/modules/config/doom-gitsigns.lua

With this patch, deprecation notice will be gone and nice
Changes for gitsigns
34deec2 ("Add config.diff_opts and deprecate fields", 2021-09-09)
use_internal_diff is now deprecated,lease use diff_opts.internal
current_line_blame_delay is now deprecated,lease use current_line_blame_opts.delay
current_line_blame_position is now deprecated,lease use current_line_blame_opts.virt_text_pos
Signed-off-by: Osamu Aoki <osamu@debian.org>

fix(modules): update gitsigns configuration

---

lua/doom/extras/keybindings/init.lua

Signed-off-by: Osamu Aoki <osamu@debian.org>

docs: correct description (split or not)

---

lua/doom/modules/config/doom-dap-ui.lua

Tested on my local setup and works.

fix(dapui): open_on_start deprecated

---

.gitignore

Swap file help recovering data when editor crashes.
Currently, doom-nvim sets swap as off.  That's OK.
But please consider excluding them in .gitignore.

feat(gitignore): ignore editor artifacts

---

doom_config.lua

Here is a patch for https://github.com/NTBBloodbath/doom-nvim/issues/134
Mode line is lines such as
`# vim:set ai si ts=2 sts=2 sw=2 et:`
This can set vim some limitted options.
---
Vim's modeline was known to be security risk.
Arbitrary code execution issue was initially addressed by Vim upstream
using sandbox approach.  Nvim developer found security bug in this
sandboxing code.  This history made Nvim to disable this feature.  Vim
distributors such as Debian also disable this feature in its default
install, too.
Considering the recent change[*] to use more restrictive whitelist
approach, use of modeline became as secure as external packages
such as securemodelines written in vimL.
[*] https://github.com/neovim/neovim/issues/2865
Signed-off-by: Osamu Aoki <osamu@debian.org>

modeline by nvim 0.5 is as secure

---

lua/doom/modules/config/doom-tree.lua

doom.core.config does not hold `config` property, so `load_config` has to be used

fix(modules): correct usage of config property

---

lua/doom/core/config/init.lua
lua/doom/core/init.lua
lua/doom/modules/config/doom-lspinstall.lua

I think the issue is due to a race condition from the part of the code that installs the LSPs running before Packer is done lazy loading nvim-lspinstall and nvim-lspconfig.  I mirrored the way nvim-treesitter works by moving the installation into the config file of `nvim-lspinstall`.  There's still some bugs that I need to iron out before this is production ready.
This is still a work in progress, open to feedback :)
Start of discussion in #87

[WIP] Fixed LSP servers not installing with +lsp in doomrc

---

lua/doom/core/config/init.lua
lua/doom/core/init.lua
lua/doom/modules/config/doom-dap-install.lua
lua/doom/modules/init.lua

The automatic installer had the same problem as #87 & #149.
Also it seems like the `ColourScheme` event wasn't triggering `nvim-dap` so I've removed lazy loading from it.  Let me know if there's another autocommand that would be more suitable. 
Additionally the api to install DAPs has changed so I've fixed that.

Fixed DAPInstall.nvim auto install

---

docs/getting_started.md
lua/doom/core/config/init.lua
lua/doom/core/init.lua
lua/doom/modules/config/doom-dap-install.lua
lua/doom/modules/config/doom-lspinstall.lua
lua/doom/modules/config/doom-treesitter.lua
lua/doom/modules/init.lua

PR that implements #150 
Using new syntax to supply a different LSP for a language.
```lua
"vue +lsp", -- default LSP
"vue +lsp(volar)", -- override LSP
```
Note: The Volar LSP hasn't been merged into nvim-lspinstall yet.
This implementation automatically uninstalls the original language LSP to avoid conflicts (i.e. vue language server and volar are incompatible).  **However, if the user removes the override, both language servers will still be installed.**  Not sure what to do about this.  I'm going to add a warning to the log file that this is the case when the override is first supplied.
Also I tried to do the pattern matching using an optional pattern match but I couldn't get it to work, quite new to lua so let me know if I can avoid duplication of searching for …

Feature: Added LSP override using `+lsp(LSP_NAME)`

---

docs/getting_started.md
lua/doom/modules/config/doom-lspmanager.lua

I have re-written the auto install portion of the LSP to address some bugs and add more features
- Previously if two languages used the same LSP but only one had the `+lsp` flag, it would install and uninstall it at the same time causing an error (this was an issue with both javascript and typescript using `tsserver` LSP).
- Supports adding more default LSPs down the line
- I also added the ability to add multiple LSP overrides, such as the documented example in `getting_started.md`.
- First determine all LSPs that need to be installed
- Determine which LSPs should be uninstalled
- Uninstall all the LSPs that ARE installed but shouldn't be (not in the ensure_installed) array.
- Install all LSPs that aren't installed but should be (not in the ensure_installed) array.
This will …

LSPManager: Fix bug with overlapping LSPs and add multiple overrides

---

lua/doom/extras/keybindings/init.lua
lua/doom/modules/config/doom-whichkey.lua

I found that the keybindings for the DAP module were just nonexistent.
I've added a couple of keybindings that set breakpoints, start a debugging session, and terminate the debugging session.
I'm not a big fan of the current keybinding for opening the debug session being set to <leader>od.  I was thinking of adding a keybinding for F8, since that is the first function key that is unused.

Added debugging keybindings

---

lua/doom/extras/keybindings/init.lua

:sweat_smile:  In the previous PR I submitted, one of the calls is missing the "opts" argument, and also the keybinding for continue had the wrong command.  This commit fixes it..

Fixed missing 'opts' param in keybinding

---

lua/doom/modules/init.lua

Sorry NTBloodBath, I should have caught this but I didn't manually update the pinned packer dependencies for dependencies that use a non-default branch.  This PR fixes this issue.

Manually update pinned packer dependencies that use a custom branch

---

lua/doom/modules/config/doom-lsp-installer.lua

My previous PR accidentally broke overrides supplied as +lsp(volar) (they did not install or setup). This PR fixes this issue.  Now PRing into the correct branch

Fix broken overrides for LSP installer

---

lua/doom/core/functions/init.lua

This PR solves #186 (no error/warn logs in :DoomReport) by loosening the ways that dates can be formatted.  Tested and working on macos with Australian time localisation.

Fixed :DoomReport not collecting logs

---

lua/doom/modules/built-in/reloader/init.lua

When editing a `doom-*.lua` file outside of your neovim config, or if editing a `doom-*.lua` file in a symlinked config (I'll use cheovim eventually) we get a nil concatenation error.  This occurs on every save and is pretty disruptive.
This PR fixes this by instead warning the user once per session.

Fixed errors when auto reload fails for doom-*.lua files.

---

lua/doom/modules/config/doom-neorg.lua
lua/doom/modules/config/doom-treesitter.lua
lua/doom/utils/init.lua

Clang is unable to compile some treesitter parsers.  This PR provides a warning #222 and directs users to #246 where they can solve their problem.  
It uses the same logic as nvim-treesitter to determine which compiler to use so it shouldn't have any false positives (unless compatibility with clang improves).

Remove gcc override for treesitter and warn clang users they may have compatibility issues.

---

lua/doom/modules/config/doom-telescope.lua

i realized by coincidence that telescope, as configured by doom-nvim, would ignore too many files.
For instance, create a folder with a file named `agit.txt` or `node_modulesaa` and run `spc f f` in doom-neovim: telescope won't list these files.
The reason is that telescope wants regexes for the ignore patterns:
>  A table of lua regex that define the files that should be ignored.
>  Example: { "^scratch/" } -- ignore all files in scratch directory
>  Example: { "%.npz" } -- ignore all npz files
>  See: https://www.lua.org/manual/5.1/manual.html#5.4.1 for more
>  information about lua regex
This PR changes the format of the telescope ignore pattern as configured by doom-nvim to more restrictive regular expressions as opposed to strings that blacklist many valid files.

fix telescope ignoring too many files due to regex

---

lua/doom/modules/config/doom-telescope.lua

i'm sorry, i was a little sloppy in my PR earlier. I realized since then that .git, .node_modules and __pycache__ are FOLDERS, not files. therefore the regex to hide them must end in /, not in $ -- same as in the telescope documentation:
> A table of lua regex that define the files that should be ignored.
> Example: { "^scratch/" } -- ignore all files in scratch directory
> Example: { "%.npz" } -- ignore all npz files
> See: https://www.lua.org/manual/5.1/manual.html#5.4.1 for more
> information about lua regex

oops, telescope ignoring pattern: these are folders not files

---

lua/doom/modules/config/doom-telescope.lua

Hi, after my PRs on main regarding this telescope ignore pattern yesterday, I realized the fix was already on the develop branch.. Except that there the `.` in .git wasn't escaped, so we would also ignore for instance a folder named `agit`. This is now the same as what's right now in the `main` branch.

telescope ignore pattern: must escape the '.'

---

lua/doom/modules/init.lua

This pull request "works around" bug #259. Good enough until the next doom-nvim release.

fix bug #259 "nvim-lspconfig broke doom stable"

---

lua/doom/modules/init.lua

Fix deprecation of:
```vim.lsp.diagnostic.get_all```

chore: Updated commit shas for pinned dependencies

---

docs/getting_started.md

This states that MacPorts only has Neovim 0.4.4 but right now it has the latest version (0.6.1). I've removed the statement
https://ports.macports.org/port/neovim/

Remove outdated MacPorts statement

---

doom_modules.lua
lua/doom/modules/config/doom-lsp-installer.lua
lua/doom/modules/config/doom-treesitter.lua

Added support for Terraform as a language to be enabled via `doom_modules.lua`. Terraform is a little weird, as it's Tree-sitter parser is simply `hcl` (the config language Terraform is written in) - hence the extra logic here.

Add Terraform support

---

lua/doom/modules/config/doom-dashboard.lua

(Bug Fixes) - changes made following [`dashboard-nvim`](https://github.com/glepnir/dashboard-nvim) Vimscript -> Lua rewrite
- add `local db = require("dashboard")`
- rewrite (Vimscript) `vim.g.dashboard_custom_section` -> (Lua) `db.custom_center`
- rewrite (Vimscript) `vim.g.dashboard_custom_footer` -> (Lua) `db.custom_footer`
- rewrite (Vimscript) `vim.g.dashboard_custom_header` -> (Lua) `db.custom_header`
- fix `custom_header` support for when user sets `config.doom.dashboard_custom_header`
- fix/update header colors (highlight groups)

[Fix] [`doom-dashboard.lua` #345]

---

lua/doom/core/functions.lua
lua/doom/modules/core/doom/init.lua
lua/doom/modules/core/treesitter/init.lua
lua/doom/modules/features/auto_install/init.lua
lua/doom/modules/features/dashboard/init.lua
lua/doom/modules/features/explorer/init.lua
lua/doom/modules/features/lsp/init.lua
lua/doom/modules/features/telescope/init.lua
lua/doom/modules/langs/utils.lua
lua/doom/utils/init.lua

Having `is_module_enabled` only takes the module names prevents us from distinguishing two modules with the same name in different sessions.

Make `is_module_enabled` depend on module section

---

init.lua
lua/doom/utils/logging.lua

When `vim.fn.stdpath('data')` does not exists, logging fails when trying to open the `doom.log` file. This both adds a check that the log file could be opened, and makes sure the data directory exists when starting neovim.

Fix error when logging to file

---

lua/doom/modules/langs/ocaml/init.lua
modules.lua
tools/Dockerfile

Uses https://ocaml.org/p/ocaml-lsp-server/ as language server that can
be installed via `opam`.
Can be tested if I add this to the Dockerfile:
```diff
diff --git a/tools/Dockerfile b/tools/Dockerfile
index 5f2d7ce..e0bc98e 100644
--- a/tools/Dockerfile
+++ b/tools/Dockerfile
@@ -36,6 +36,9 @@ RUN npm i -g chokidar-cli
RUN pacman -Sy hyperfine --noconfirm
+# OCaml
+RUN pacman -Sy opam diffutils patch ocaml --noconfirm
+
RUN groupadd doom
RUN useradd -m -g doom doom
@@ -46,6 +49,8 @@ RUN chown -R ${UNAME}:${GNAME} /usr/local/lib/node_modules/
USER doom
WORKDIR /home/doom
+RUN opam init --disable-sandboxing && opam install ocaml-lsp-server -y
+
COPY _docker_entry.sh /usr/local/bin/
```
And then run `eval $(opam env); nvim` inside.
I've been using this for quite a while on 3.3.0, but the port …

feat(ocaml): add language

---

lua/doom/core/init.lua
lua/doom/modules/features/explorer/init.lua

Muscle memory on `:e .` and `:e ~/`. Used to work on previous version of Doom, but only shows an error message `. is a directory` on 4.0.x.
This was handled by `netrw` which is now entirely disabled (to optimize startup time I assume).
First of all, when the `netrw` feature is used instead of `explorer` we shouldn't disable loading netrw :)
Next, when explorer is used an autocommand is needed to toggle loading it when editing directories. This wouldn't be needed if its `setup()` function was run, but the module is lazy-loaded to decrease startup time, so we need this autocmd.
See `:h nvim-tree-api` (after loading nvim-tree, e.g. by editing a dir) for a stable way to call nvim-tree functions.

Fix netrw and explorer features

---

lua/doom/modules/features/statusline/init.lua

Some colorschemes (e.g. Zenburn) have a light foreground for the
statusline, and most of the special* colors are light too, resulting in
very low contrast.
In such a case swap statusline background/foreground colors.
This makes `ZenBurn` theme's statusline readable, even though it doesn't use the statusline colors the theme intended.
This is more of a workaround, but works for me so far. 
Perhaps a better way would be to avoid using so many other colors that were not intended for the statusline and instead try to just tweak the bold/etc. attributes? What do you think?
FWIW with the previous version of Doom the statusline worked without needing to tweak colors.

fix(statusline): increase contrast

---

lua/doom/modules/core/doom/init.lua

explorer/init.lua already defines the proper one that calls `NvimTreeToggle`.
`Lexplore` is a netrw command (disabled by default),
and `Lexplore%s` looks like a typo.
Fixes https://github.com/NTBBloodbath/doom-nvim/issues/374

fix(explorer): delete duplicate keybinding

---

doc/doom_nvim_modules.norg
docs/modules.md
lua/doom/modules/langs/nix/init.lua
modules.lua

Uses [`rnix-lsp`](https://github.com/nix-community/rnix-lsp) as language-server for Nix files.
For Nix users the `rnix-lsp` is available on nixpkgs.
Enabling the linter feature enable the following:
- Code Actions and diagnostics using `statix`
- Diagnostics using `deadnix` for dead code
- Formatting using `nixpkgs-fmt`
All of those binaries are also available on nixpkgs and can be individaually disables (or switched in the case of `nixpkgs-fmt`)

feat(langs,nix): Add nix language support

---

lua/doom/modules/features/comment/init.lua

The call convention for the `Comment.nvim` plugin has changed on the latest version.
Previously the methods were flattened in the required object with `_` separators, now they are organized in a nested structure using metatables.
- Added upstream on numToStr/Comment.nvim#183

fix(comments): Update plugin call convention

---

lua/doom/modules/core/doom/init.lua
lua/doom/modules/features/dashboard/init.lua

- The "Open Documentation" item on the dashboard show the shortcut `SPC D d`, but that shortcut is not set.
- The "Load Last Session" item shows the shortcut `SPC s r`, that shortcut is to continue the last _search_, not session. The last session is `SPC q r`

fix(dashboard): Fix shortcuts shown on dashboard

---

tools/install.sh

has_found_directory always equalled an empty string so if nvim-old already existed it would fail to move to nvim-old-1 and would then fail when installing doom-nvim.
Added function to check whether doom-nvim is specifically installed in the config and, if so, backs the config up to doom-nvim-old. If doom is installed then the default backup_existing_config function doesn't run.

Fixed backup dirs & added doom-nvim installed check

---

lua/doom/modules/features/explorer/init.lua

I have a folder with "git" in name (git-tools), and I have no way to have it displayed. 
Dive into code, and likely the filter regex is incorrect.

fix: neotree not display dir with "git" in name

---

lua/doom/modules/features/explorer/init.lua

When "LSP" module is disabled and "explorer" module enabled, everytime when nvimtree was being loaded, error occurs in  tbl_deep_extend for nvim config because of uninitialized variable

fix: nvim-tree broken when lsp disabled

---

lua/doom/modules/features/terminal/init.lua

The key to open the terminal, F4 by default, is not listed in the hotkeys that cause lazy.nvim to load the terminal module.  As a result, the hotkey to open the terminal does not work unless the terminal module has been loaded by lazy.nvim (which, with current default configuration, only happens if the user manually enters :TermExec or :ToggleTerm)

Fixed Terminal not opening via hotkey
